services:
  mysql:
    image: mysql:8.0
    container_name: tp5_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp5_db
      MYSQL_USER: tp5_user
      MYSQL_PASSWORD: tp5_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
